### ISSUE TITLE
Pairing method

### ISSUE THREAD

**Issue by 18202835972** [jareksedy/WebOSClient#1]
Hi, I noticed that other remote control apps on the App Store use pin codes to pair. Does your project support pairing using pin codes?

**Comment by jareksedy** [comment]
Hello, right now it does not support pairing via pin code. I am planning to add it in the next future version, if it's possible at all. Some research needed here.

**Comment by jareksedy** [comment]
Hi there! Version 1.5.0 now supports pairing with pin.
