### ISSUE TITLE
Open apps like netflix, amazon etc

### ISSUE THREAD

**Issue by Coger541** [jareksedy/WebOSClient#2]
Hi, 
Good library for Lg tv control

But is there any feature to open app like netflix or amazon or disney through command

**Comment by jareksedy** [comment]
Hey there,

sure, just invoke with the desired app id

client?.send(.launchApp(appId: "netflix"))  

to get the list of installed apps with their ids use

client?.send(.listApps) 

please also see the example app 'Apps' section.
