### ISSUE TITLE
Run in LG simulator

### ISSUE THREAD

**Issue by Coger541** [jareksedy/WebOSClient#4]
Hello @jareksedy 

Can I control LG simulator in mac by running this project in to iPhone simulator as I don't have LG smart tv ?

Thanks

**Comment by jareksedy** [comment]
Hi @Coger541 !

I've always tested it on a real device. Could you provide me with a link to the LG simulator you're using, i'll try to check if it works.

**Comment by Coger541** [comment]
Yes Sure

https://webostv.developer.lge.com/develop/tools/emulator-installation

And do you also have any implementation to control Fire TV or Vizio Smartcast TV ?

**Comment by jareksedy** [comment]
Understood, i'm afraid there's no way to connect to a LG simulator, the simulator simply does not allow that.

> And do you also have any implementation to control Fire TV or Vizio Smartcast TV ?
No this package is solely dedicated to webOS-based TVs (LG Smart TVs).

**Comment by Coger541** [comment]
Ok thanks a lot for help
