### ISSUE TITLE
How to find Apps ID

### ISSUE THREAD

**Issue by Coger541** [jareksedy/WebOSClient#5]
How to find out other apps Id like youtube, disney, prime video etc. I have app ID for other apps but those are for android smart tv not LG like 
For prime video app Id is: https://app.primevideo.com
And for spotify: spotify://

Does these android apps Id also works for LG ?

At here
client?.send(.launchApp(appId: "netflix"))

**Comment by Coger541** [comment]
@jareksedy any suggestion ??

**Comment by jareksedy** [comment]
Sure, that's easy, first you send the command to get the list of all installed apps

`requestId = client?.send(.listApps)` 

where `client` is your WebOSClient instance, and requestId some string variable.

then you handle the response in the `didReceive` delegate method like that:

```
    func didReceive(_ result: Result<WebOSResponse, Error>) {
        if case .success(let response) = result, response.id == requestId {
             let applications: [WebOSResponseApplication] = response.payload?.applications ?? []
        }
}
```
