### ISSUE TITLE
Touchpad Keys

### ISSUE THREAD

**Issue by Coger541** [jareksedy/WebOSClient#6]
Hello @jareksedy 

I did not find any touchpad keys in your project, I even also try to search on google but did not get it

Do you have any idea regarding it

Thanks

**Comment by Coger541** [comment]
Hello @jareksedy 

I am sorry, I think its implemented in your library already, can you please confirm that these are used for padding

client?.sendKey(.move(dx: 10, dy: 10))
client?.sendKey(.click)

**Comment by jareksedy** [comment]
@Coger541  Yeah, sorry for late reply. This is it, you got it.

**Comment by Coger541** [comment]
Ok Thanks
